#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ ! -f "$ROOT_DIR/.env" ]; then
  echo "Error: Missing .env at repo root."
  echo "Run: make env-sync (for local) or cp .env.example .env"
  exit 1
fi

set -o allexport
source "$ROOT_DIR/.env"
set +o allexport

OUT_DIR="$ROOT_DIR/apps/ios/VoCal/Generated"
mkdir -p "$OUT_DIR"

cat > "$OUT_DIR/Environment.generated.swift" <<EOF
// AUTO-GENERATED by scripts/generate_ios_env.sh
// Do not edit manually. Run: make ios-env

import Foundation

enum EnvironmentConfig {
    static let supabaseURL = URL(string: "${SUPABASE_URL}")!
    static let supabaseAnonKey = "${SUPABASE_ANON_KEY}"
    static let apiBaseURL = "${API_BASE_URL:-http://127.0.0.1:8000}"
    static let mapboxAccessToken = "${MAPBOX_ACCESS_TOKEN:-}"
}
EOF

echo "✓ Wrote $OUT_DIR/Environment.generated.swift"
