#!/bin/sh

# Xcode Cloud post-clone hook.
#
# Two things a fresh Xcode Cloud clone is missing, both because they are gitignored:
#
#   1. VoCal.xcodeproj — generated by XcodeGen from project.yml (.gitignore: *.xcodeproj).
#      Without it the build fails: "Project VoCal.xcodeproj does not exist".
#
#   2. Package.resolved — it normally lives INSIDE the generated xcodeproj at
#      project.xcworkspace/xcshareddata/swiftpm/, so it's gitignored too. Xcode Cloud runs
#      with automatic Swift Package resolution DISABLED and REQUIRES a committed
#      Package.resolved ("a resolved file is required when automatic dependency resolution
#      is disabled"). The earlier approach — running `xcodebuild -resolvePackageDependencies`
#      here to WRITE that file — cannot work: resolution is disabled in this environment, so
#      there is nothing to write it from (chicken-and-egg; Build 21 died exactly here, exit 74).
#
# Fix: we commit the resolved graph at ci_scripts/Package.resolved (a tracked path, refreshed
# whenever project.yml's package requirements change) and COPY it into the workspace location
# after generating the project. Xcode Cloud then archives against the committed pins and fetches
# those exact revisions — which is both what it wants AND a reproducible build.

set -e

cd "$CI_PRIMARY_REPOSITORY_PATH/apps/ios"

echo "[ci_post_clone] ensuring xcodegen…"
brew list xcodegen >/dev/null 2>&1 || brew install xcodegen

echo "[ci_post_clone] generating VoCal.xcodeproj from project.yml…"
xcodegen generate

echo "[ci_post_clone] placing committed Package.resolved into the workspace…"
SWIFTPM_DIR="VoCal.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
mkdir -p "$SWIFTPM_DIR"
cp ci_scripts/Package.resolved "$SWIFTPM_DIR/Package.resolved"

echo "[ci_post_clone] done. Package.resolved in place:"
head -4 "$SWIFTPM_DIR/Package.resolved"
