#!/bin/sh

# Xcode Cloud post-clone hook.
#
# VoCal.xcodeproj is generated by XcodeGen from project.yml and is gitignored
# (.gitignore: *.xcodeproj). A fresh Xcode Cloud clone therefore has only
# project.yml, so the build fails with:
#     Project VoCal.xcodeproj does not exist at apps/ios/VoCal.xcodeproj
# Regenerate the project here, before Xcode Cloud resolves packages and builds.
#
# Xcode Cloud runs this automatically after cloning the primary repository,
# because it lives in apps/ios/ci_scripts/ (the folder containing the project).

set -e

echo "[ci_post_clone] installing xcodegen via Homebrew…"
brew install xcodegen

echo "[ci_post_clone] generating VoCal.xcodeproj from project.yml…"
cd "$CI_PRIMARY_REPOSITORY_PATH/apps/ios"
xcodegen generate

# Xcode Cloud runs with automatic Swift Package resolution DISABLED and requires a
# Package.resolved at VoCal.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/. Because
# the project is generated fresh here, that file never exists at clone time and the archive
# fails ("a resolved file is required when automatic dependency resolution is disabled").
# Resolve explicitly now to write it before the build/archive step runs.
echo "[ci_post_clone] resolving Swift package dependencies (writes Package.resolved)…"
xcodebuild -resolvePackageDependencies -project VoCal.xcodeproj -scheme VoCal

echo "[ci_post_clone] done: $(ls -d VoCal.xcodeproj) + $(ls VoCal.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved)"
